print("Este es un entero: ","5", type(5))
print("Este es un float: ","5.5", type(5.5))
print("Este es un numero complejo: ","3+1j", type(3+1j))
print("Este es un numero booleano: ","True", type(True))
print("\nRepresentacion de diferentes bases numericas: ")
print("Numero en Octal: ", 0o123)
print("Numero en Hex: ", 0x123)
print("\nNumero en notacion cientifica flotante: ",0.00000000000000001)
print("Este es un texto (String): A juan le dicen \"juanito\" sus amigos")